# Generated by Django 3.1.6 on 2021-02-03 14:12

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210203_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [74.6370662278128, 42.87254474538025], 'marker_color': 'blue', 'zoom': 10}),
        ),
    ]
